# permissions for end users to view interfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: interface-viewer-role
rules:
- apiGroups:
  - route6.io
  resources:
  - interfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route6.io
  resources:
  - interfaces/status
  verbs:
  - get
