# permissions for end users to view nats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nat-viewer-role
rules:
- apiGroups:
  - route6.io
  resources:
  - nats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route6.io
  resources:
  - nats/status
  verbs:
  - get
